// Copyright(C) 2022, ATA Engineering, Inc.
// 
// This program is free software; you can redistribute it and /or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 3 of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the GNU
// Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with this program; if not, see
// < https://www.gnu.org/licenses/lgpl-3.0.html>.
// 
// Some of the source code for this program was generated with the 
// Pointwise Plugin SDK, and is subject to the Cadence Public License
// Version 1.0.


/****************************************************************************
 *
 * c++ implementation of runtimeWrite(), runtimeCreate(), and runtimeDestroy()
 *
 * (C) 2021 Cadence Design Systems, Inc. All rights reserved worldwide.
 *
 ***************************************************************************/

/* DO NOT EDIT THIS FILE!

 * To make plugin specific changes, you should edit CaeUnsLociChem.cxx

 * DO NOT EDIT THIS FILE!
 */

#include "apiCAEP.h"
#include "apiCAEPUtils.h"
#include "apiGridModel.h"
#include "apiPWP.h"
#include "runtimeWrite.h"

#include "CaeUnsLociChem.h"


/**************************************/
PWP_BOOL
runtimeWrite(CAEP_RTITEM *pRti, PWGM_HGRIDMODEL model,
    const CAEP_WRITEINFO *pWriteInfo)
{
    CaeUnsLociChem plugin(pRti, model, pWriteInfo);
    return plugin.run();
}

PWP_BOOL
runtimeCreate(CAEP_RTITEM *pRti)
{
    return CaeUnsLociChem::create(*pRti);
}

PWP_VOID
runtimeDestroy(CAEP_RTITEM *pRti)
{
    return CaeUnsLociChem::destroy(*pRti);
}
